"use client";

import { TEST_PROMPTS } from "@/lib/test-prompts";

interface EmptyStateProps {
  onPick: (prompt: string) => void;
}

export function EmptyState({ onPick }: EmptyStateProps) {
  return (
    <div className="scroll-area flex-1 overflow-y-auto">
      <div className="mx-auto max-w-3xl px-6 md:px-10 py-12 md:py-16">
        {/* Hero */}
        <div className="text-center mb-12 md:mb-16">
          <div className="text-[10px] uppercase tracking-[0.3em] text-[var(--secondary)] mb-5 font-mono">
            Prototype · v0.1
          </div>
          <h2 className="font-display text-4xl md:text-6xl font-light tracking-tight leading-[1.05] text-[var(--foreground)]">
            What can{" "}
            <em className="font-medium italic text-accent">widgets</em>
            <br />
            do for chat?
          </h2>
          <p className="mt-6 max-w-md mx-auto text-sm text-[var(--secondary)] leading-relaxed">
            Each reply is a free-form HTML widget generated by the model. Pick any
            prompt below to see what the selected mode produces.
          </p>
        </div>

        {/* Prompt sections — 2 column on md+ */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-7">
          {TEST_PROMPTS.map((group) => (
            <div key={group.kind}>
              <div className="flex items-center gap-3 mb-2.5">
                <span className="text-[10px] font-mono uppercase tracking-[0.2em] text-[var(--secondary)]">
                  {group.label}
                </span>
                <span className="flex-1 h-px bg-[var(--border)]" />
              </div>
              <div className="flex flex-wrap gap-2">
                {group.prompts.map((p) => (
                  <button
                    key={p}
                    onClick={() => onPick(p)}
                    className="text-xs px-3 py-1.5 border border-[var(--border)] rounded-full bg-[var(--surface)] hover:border-accent hover:bg-accent/5 hover:text-[var(--foreground)] text-[var(--foreground)] transition-colors text-left leading-snug"
                  >
                    {p}
                  </button>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
