"use client";

import { Library } from "lucide-react";

interface EmptyStateProps {
  onOpenPrompts: () => void;
}

export function EmptyState({ onOpenPrompts }: EmptyStateProps) {
  return (
    <div className="scroll-area flex-1 overflow-y-auto">
      <div className="mx-auto max-w-2xl px-6 md:px-10 py-16 md:py-24">
        <div className="text-center">
          <div className="text-[10px] uppercase tracking-[0.3em] text-[var(--secondary)] mb-5 font-mono">
            Prototype · 22 widgets · 44 prompts
          </div>
          <h2 className="font-display text-4xl md:text-6xl font-light tracking-tight leading-[1.05] text-[var(--foreground)]">
            What can{" "}
            <em className="font-medium italic text-accent">widgets</em>
            <br />
            do for chat?
          </h2>
          <p className="mt-6 max-w-md mx-auto text-sm text-[var(--secondary)] leading-relaxed">
            Each reply is a free-form HTML widget generated by the model. Type
            a question below, or browse the prompt library for ideas.
          </p>

          <button
            type="button"
            onClick={onOpenPrompts}
            className="mt-8 inline-flex items-center gap-2 text-xs uppercase tracking-[0.2em] font-mono px-4 py-2 rounded-full border border-[var(--border)] bg-[var(--surface)] text-[var(--foreground)] hover:border-accent hover:text-accent transition-colors"
          >
            <Library className="h-3.5 w-3.5" strokeWidth={1.5} />
            Open prompt library
          </button>
        </div>
      </div>
    </div>
  );
}
